version: '3'
services:
  mysql:
    restart: unless-stopped
    image: {mysql-test}
    container_name: mariadb10.4.7_no-volumes
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hello
    network_mode: "host"