global:                  # 全局设置，可以被覆盖
  # scrape_interval:     15s # 默认值为 15s，用于设置每次数据收集的间隔
  evaluation_interval: 15s

  external_labels:   # 所有时间序列和警告与外部通信时用的外部标签
    monitor: 'codelab-monitor'

# 告警管理配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - 127.0.0.1:9093

rule_files: # 警告规则设置文件
  - '/etc/prometheus/*.rules'

# 用于配置 scrape 的 endpoint  配置需要 scrape 的 targets 以及相应的参数
# 抓取(pull)，即监控目标配置。默认只有主机本身的监控配置
scrape_configs:
  # 监控目标的label（这里的监控目标只是一个metric，而不是指某特定主机，可以在特定主机取多个监控目标），在抓取的每条时间序列表中都会添加此label
  - job_name: 'prometheus'  # 一定要全局唯一, 采集 Prometheus 自身的 metrics

    # 覆盖全局的 scrape_interval
    scrape_interval: 5s

    static_configs:  # 静态目标的配置
      - targets: ['127.0.0.1:9090']    # Prometheus的endpoint

  - job_name: 'node'  # 一定要全局唯一, 采集本机的 metrics，需要在本机安装 node_exporter

    scrape_interval: 10s

    static_configs:
      - targets: ['15.16.17.50:9100', '15.16.17.51:9100', '15.16.17.60:9100', '15.16.17.70:9100', '15.16.17.71:9100', '15.16.17.80:9100', '15.16.17.81:9100', '15.16.17.100:9100', '15.16.17.89:9100', '15.16.17.40:9100', '15.16.17.20:9100', '15.16.17.149:9100', '15.16.17.110:9100', '15.16.17.85:9100', '52.80.64.79:9100', '52.80.22.40:9100']  # node_exporter 的 endpoint

  - job_name: 'pushgateway'
    scrape_interval:     1m
    static_configs:
      - targets: ['127.0.0.1:9091']
        labels:
          instance: pushgateway
    honor_labels: true
